apiVersion: v1
kind: Service
metadata:
  name: dingtalk
  namespace: kube-monitoring
  labels:
    app: dingtalk
  annotations:
    prometheus.io/scrape: 'false'
spec:
  selector:
    app: dingtalk
  type: NodePort
  ports:
  - name: dingtalk
    port: 8060
    protocol: TCP
    targetPort: 8060
