apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: kube-monitoring
  labels:
    app: node-exporter
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: node-exporter
  type: NodePort
  ports:
  - name: node-exporter
    port: 9100
    protocol: TCP
    targetPort: 9100